#
# docker-compose.yaml
#
# Cleanup docker-compose file.
#
# @author Robert Carr <bob@lab183.com>
# @copyright 2020 Lab183, LLC. -- All rights reserved.

--- 
    # Set compose api version
    version: "3.7"
     
    # Define the containers to build as docker-compose services
    services:
      # perform an image cleanup every hour
      image_cleaner:
        image: docker
        command: sh -c "while true; do docker image prune -af; sleep 86400; done"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        deploy:
          mode: global
    